### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#35]
Hi @Upasana1807, 

Please correct the layout as you can notice that some of the elements have moved at right side.

REF: 
![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/4e40c816-496b-454a-bd5f-95126cecbf4d)

Thank You.

**Comment by Upasana1807** [comment]
Hey,
@Sne2003 as per your request, I've aligned the elements. Now you can can go check if it is properly working or not.
![Screenshot (377)](https://github.com/Upasana1807/Electoral-Application/assets/155513433/9f5a5431-05db-4fcf-8922-ff4062e737b6)

**Comment by Sne2003** [comment]
Ok.
Thank You.
