### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#36]
Hi @Raumyakoley ,

Please make all the icons of same size!!

REF:
![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/fe7e3452-28fc-4586-8352-ca84958596d8)

Thank You.

**Comment by Raumyakoley** [comment]
SOLVE

**Comment by Sne2003** [comment]
Screenshot?

**Comment by Raumyakoley** [comment]
![Screenshot 2024-05-04 233159](https://github.com/Upasana1807/Electoral-Application/assets/155466170/967f9603-7981-4e8b-9005-8c26ebf697b5)

**Comment by Sne2003** [comment]
Make the second icon smaller or the third icon bigger, this second icon is not correctly sized with the third icon.

**Comment by Raumyakoley** [comment]
![Uploading Screenshot 2024-05-11 212732.png…]()

**Comment by Raumyakoley** [comment]
![Uploading login issue.png…]()

**Comment by Raumyakoley** [comment]
![login issue](https://github.com/Upasana1807/Electoral-Application/assets/155466170/3a286082-cc99-4b10-b0f6-9f056ebb92fb)

**Comment by Sne2003** [comment]
Ok
Thank You
