### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#37]
Hi @Upasana1807,

Please correct the footer:
1)Use icons of same style and colour.
2)Align every components correctly in a right manner because it is looking substandard.

![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/2f4b68b3-9882-41ce-939c-b3d3049de6cf)

Thank You.

**Comment by Upasana1807** [comment]
Hey @Sne2003 I have made the changes you asked. Please let me know if it is okay or there is something left.

![image](https://github.com/Upasana1807/Electoral-Application/assets/155513433/3f1d9e23-d50d-4fca-9fad-38c61a618537)

**Comment by Sne2003** [comment]
Hey @Upasana1807,

This is not correctly assigned.

![Screenshot 2024-05-12 015831](https://github.com/Upasana1807/Electoral-Application/assets/127588865/1b7b422e-1b5a-4e24-81dc-6e46790fe60b)

**Comment by Upasana1807** [comment]
Hey, @Sne2003 I have done the required changes. Please check it once.

![image](https://github.com/Upasana1807/Electoral-Application/assets/155513433/d17b3821-7366-4bb9-9d6b-685a04a7a9e2)

**Comment by Upasana1807** [comment]
@Sne2003 I have merged the branch because in other pages the footer was not showing properly. Let me know if any changes required.

**Comment by Sne2003** [comment]
OK
Thank You
