### ISSUE TITLE
Voter Details Page 

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#38]
Hi @Raumyakoley,

As you can see everything has shifted towards right so align everything properly.

![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/3a017fac-2f2c-448d-b288-7b387a06c0fe)

Thank You.

**Comment by Raumyakoley** [comment]
SOLVE

**Comment by Sne2003** [comment]
Screenshot?

**Comment by Raumyakoley** [comment]
![Screenshot 2024-05-04 233005](https://github.com/Upasana1807/Electoral-Application/assets/155466170/0ee83fee-8d24-4b50-ada7-619fa7934d9b)

**Comment by Sne2003** [comment]
It is still not aligned correctly, please correct it.

**Comment by Sne2003** [comment]
![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/f2a16a6e-dfa6-4c39-9fda-7d1c193bb60b)

Hey @Raumyakoley ,
See every word is not aligned in a single line so it is not looking good, so aligned them properly in a line.

**Comment by Raumyakoley** [comment]
![Uploading Screenshot 2024-05-11 205424.png…]()

**Comment by Raumyakoley** [comment]
![Uploading Screenshot 2024-05-11 205424.png…]()

**Comment by Raumyakoley** [comment]
![voterditels](https://github.com/Upasana1807/Electoral-Application/assets/155466170/d4ff9123-7bf4-4b02-86b4-e999e98b03be)

**Comment by Sne2003** [comment]
OK
Thank You.
