### ISSUE TITLE
Candidate Dashbord

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#39]
Hi @Raumyakoley,

The Log Out button has shifted to left so please align it correctly at the centre.

![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/d1d16887-6d21-4483-bcca-d7827a09312f)

Thank You.

**Comment by Raumyakoley** [comment]
SOLVE

**Comment by Sne2003** [comment]
Screenshot?

**Comment by Raumyakoley** [comment]
![Screenshot 2024-05-04 232748](https://github.com/Upasana1807/Electoral-Application/assets/155466170/2e2aaf1b-2fb7-4bd9-a2c3-03d9b8fe9cfe)

**Comment by Sne2003** [comment]
Ok.
Thank You.
