### ISSUE TITLE
Candidate Form

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#40]
Hi @Upasana1807,

Please correct this button properly.
1)The first picture represents that the button is normal until it is hovered.
2) The second picture represents that after getting hovered the button is behaving oddly as you can see it is getting zoomed & hazy unnecessarily. As the buttons of the other pages are not behaving like that. 

![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/1cdac6e8-20ec-4943-a557-21354defd654)

![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/65c97a15-71a1-4125-b1c7-192053bde5d6)

Thank You.

**Comment by Upasana1807** [comment]
Hey, @Sne2003 the above mentioned issue is solved. Please check it once.

**Comment by Sne2003** [comment]
Screenshot?

**Comment by Upasana1807** [comment]
![image](https://github.com/Upasana1807/Electoral-Application/assets/155513433/68204cab-8f5b-457e-a026-0e4aa1d9af39)

@Sne2003  this is the screenshot of the button after hovering

**Comment by Sne2003** [comment]
Ok
Thank You.
