### ISSUE TITLE
Candidate Form

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#41]
Hi @Upasana1807,

As you can see the button is not correctly aligned in the center so please correct it.

![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/89a30bb5-4a5f-4248-b806-6cf1fdf4cbbc)

Thank You.

**Comment by Upasana1807** [comment]
Hey, @Sne2003 the issue is solved, which you mentioned previously. Now, the SUBMIT button is correctly aligned in the center. check it once and merge my pull request.

![image](https://github.com/Upasana1807/Electoral-Application/assets/155513433/eb02fa16-cb65-4018-9fbb-50770663dad6)

**Comment by Sne2003** [comment]
Ok
Thank You.
