### ISSUE TITLE
Countdown Page

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#42]
Hi @Raumyakoley,

I am only able to get an exit from this page to home page but nothing is linked to this page so i can get an entry to this countdown page.

![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/cf444b97-7d2f-4e2d-9a71-73bd078a18f8)

Thank You.

**Comment by Raumyakoley** [comment]
not solve

**Comment by Sne2003** [comment]
What is the reason?

**Comment by Raumyakoley** [comment]
where i link it ??

**Comment by Sne2003** [comment]
Hey @Upasana1807 please look after this.

**Comment by Upasana1807** [comment]
Hey @Sne2003 @Raumyakoley this issue is solved. I've merged it with the voter details page. 
@Sne2003 you can close the issue now.

**Comment by Sne2003** [comment]
Ok
Thank You.
