### ISSUE TITLE
Countdown Page

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#43]
Hi @Upasana1807,

Please remove the white border from the last box.

![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/0aafe639-fc37-47d6-8efd-55ec1d547147)

Thank You.

**Comment by Upasana1807** [comment]
![image](https://github.com/Upasana1807/Electoral-Application/assets/155513433/fd138b4b-20a9-48c2-a8c5-f7de0aba9ee0)


Hey, @Sne2003 the issue is solved, which you mentioned previously. Now,  I removed the white border from the last box. check it once and merge my pull request.

**Comment by Upasana1807** [comment]
![image](https://github.com/Upasana1807/Electoral-Application/assets/155513433/88cbeb60-b29a-4a45-a9e2-0fcfd5761331)


But @Sne2003 I have another concern, why it is showing in minus? and the timer is increasing. Please look into this matter.

**Comment by Sne2003** [comment]
Ok
Thank You
Looking forward to your concern.
