### ISSUE TITLE
Declaring Page

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#44]
Hi @Raumyakoley,

I am only able to get an exit from this page to home page but nothing is linked to this page so i can get an entry to this declaring page

![Screenshot 2024-04-20 012540](https://github.com/Upasana1807/Electoral-Application/assets/127588865/c8c47106-9413-4af9-bf55-321c44ee2441)

Thank You,

**Comment by Raumyakoley** [comment]
SOLVE

**Comment by Sne2003** [comment]
Okay
