### ISSUE TITLE
Declaring Page Button

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#45]
Hi @Upasana1807,

Please make this button as like other buttons of the other pages. This button is having no border radius and is having a border colour that'swhy it is not looking similar to other buttons.

![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/78521695-766a-4fc0-bf4e-5fb740d8033f)

Thank You.

**Comment by Upasana1807** [comment]
![image](https://github.com/Upasana1807/Electoral-Application/assets/155513433/71f151e3-3efb-4918-9458-a7f8b23f7112)


Hey, @Sne2003 the issue is solved, which you mentioned previously. check it once and merge my pull request.

**Comment by Sne2003** [comment]
Ok
Thank You.
