### ISSUE TITLE
Admin Page

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#46]
Hi @Raumyakoley,

Please fill every space of the boxes with the utmost information because it is looking substandard and this kind of websites should not have this kind of interface.

![Screenshot 2024-04-22 173444](https://github.com/Upasana1807/Electoral-Application/assets/127588865/07777820-5b81-4d0b-a991-cc821881c1f4)

Check the highlighted part.

Thank You.

**Comment by Sne2003** [comment]
Screenshot?

**Comment by Raumyakoley** [comment]
![Screenshot 2024-05-04 232411](https://github.com/Upasana1807/Electoral-Application/assets/155466170/349d7c78-edd3-40fe-bcfe-e91d5ac03e67)

**Comment by Sne2003** [comment]
Ok.
Thank You.
