### ISSUE TITLE
Voting Page

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#48]
Hi @Upasana1807,

Please rectify this essential page:
1)There is no indication of vote, that means there should be a small box showing an indication after user clicks on their respective vote button so that they can get assured where they are voting.
2) I mean if I click on vote, the vote gets accepted but this should not happen as because if any user by mistakenly clicks the vote and that might not be the right button they wanted to click so there must be a two step verification.
3)So after clicking the vote button, the box beside that respective vote button should glow so the user gets confirmed where they are voting 
4)After that there should be a submit button to submit the vote,

![Screenshot 2024-04-22 173411](https://github.com/Upasana1807/Electoral-Application/assets/127588865/06dac216-6ea9-41c4-b70d-22f5296c4a2e)

Thank You.

**Comment by Upasana1807** [comment]
Hey, @Sne2003 
   I understood your concern, but I'd like to request you to please handover this issue to another member. As there are pages, which I need to make responsive and of whom I need to create a CSS file too.

**Comment by Sne2003** [comment]
I acknowledge your efforts. @Upasana1807 

Hey @Raumyakoley please look after this issue and solve it accordingly.

**Comment by Raumyakoley** [comment]
WE NEED TO MAKE SOME MORE PAGE TO SOLVE THIS ISSUE

**Comment by Sne2003** [comment]
I don't think so @Raumyakoley 

What's your POV? @Upasana1807

**Comment by Raumyakoley** [comment]
![Uploading Screenshot 2024-05-11 202744.png…]()

**Comment by Raumyakoley** [comment]
![Uploading Screenshot 2024-05-11 202744.png…]()
