### ISSUE TITLE
Voting Page

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#49]
Hi @Upasana1807,

Please make sure that these buttons are correctly aligned at the center of the boxes.

![Screenshot 2024-04-22 173411](https://github.com/Upasana1807/Electoral-Application/assets/127588865/29a79275-7f74-4d54-910c-ee8399b161cd)

Thank You.

**Comment by Upasana1807** [comment]
Hey,
@Sne2003 as per your request, I've made sure that these buttons are correctly aligned at the center of the boxes.

 Now you can can go check if it is properly working or not.
![Screenshot (378)](https://github.com/Upasana1807/Electoral-Application/assets/155513433/428a1e9e-7f2d-45b3-b80b-c16835b0fde3)

**Comment by Sne2003** [comment]
Ok.
Thank You.
