### ISSUE TITLE
Admin Dashbord Page

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#50]
Hi @Raumyakoley,

Please make sure that these buttons are aligned ate the center of the boxes.

![Screenshot 2024-04-22 230257](https://github.com/Upasana1807/Electoral-Application/assets/127588865/7d58ecba-b7f4-4c52-8fa8-eba878b220c7)

Thank You.

**Comment by Raumyakoley** [comment]
SOLVE

**Comment by Sne2003** [comment]
Screenshot?

**Comment by Raumyakoley** [comment]
![Screenshot 2024-05-04 232411](https://github.com/Upasana1807/Electoral-Application/assets/155466170/e315c20d-7c33-4a68-91af-852fd502a028)

**Comment by Sne2003** [comment]
ok,
