### ISSUE TITLE
Voting Pge

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#51]
Hi @Raumyakoley ,

Please fill every space of the boxes with the utmost information because it is looking substandard and this kind of websites should not have this kind of interface.

![Screenshot 2024-04-22 173411](https://github.com/Upasana1807/Electoral-Application/assets/127588865/82a71296-b955-4ef0-9555-c3dbd0be86ec)

Check the highlight part

Thank You.

**Comment by Raumyakoley** [comment]
SOLVE

**Comment by Sne2003** [comment]
Screenshot?

**Comment by Raumyakoley** [comment]
![Screenshot 2024-05-04 232309](https://github.com/Upasana1807/Electoral-Application/assets/155466170/577b820c-effc-466c-8b6a-3eeeff11ca79)

**Comment by Sne2003** [comment]
OK.
Thank You.
