### ISSUE TITLE
Candidate Nomination Page

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#52]
Hi @Upasana1807,

Same things should be written on each boxes!!
1)So the first box should be written as "Enter the name of the candidate" instead of "Enter the candidate name".

![Screenshot 2024-04-23 012002](https://github.com/Upasana1807/Electoral-Application/assets/127588865/fc02682a-bd52-45ec-8843-703984be452f)

Thank You.

**Comment by Upasana1807** [comment]
Hey, 
@Sne2003 as per your request, I've changed the placeholder of the particular box. Now you can can go check if it is properly working or not.

**Comment by Upasana1807** [comment]
![Screenshot 2024-05-01 234339](https://github.com/Upasana1807/Electoral-Application/assets/155513433/4ebc6386-a679-44aa-abda-6e9bda30b148)

**Comment by Sne2003** [comment]
Ok done. 
Thank You.
