### ISSUE TITLE
Candidate Form Page

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#53]
Hi @Upasana1807,

After clicking the submit button this page is not redirecting to any page.

![Screenshot 2024-04-23 013834](https://github.com/Upasana1807/Electoral-Application/assets/127588865/7b172543-851d-4194-8ea2-2a3d74c75637)
![Screenshot 2024-04-23 013909](https://github.com/Upasana1807/Electoral-Application/assets/127588865/74ec8399-8663-4ffb-a854-3171eef277a6)

It should redirect to this page:

![Screenshot 2024-04-23 014217](https://github.com/Upasana1807/Electoral-Application/assets/127588865/44854907-bc19-471d-a29d-ada1d98e611f)

Connect this two pages.

Thank You.

**Comment by Upasana1807** [comment]
Hey, 
@Sne2003 as per your request, I've linked those two pages. Now you can can go check if it is properly working or not.

**Comment by Sne2003** [comment]
Ok done
Thank You.
