### ISSUE TITLE
Countdown page

### ISSUE THREAD

**Issue by Upasana1807** [Upasana1807/Electoral-Application#64]
Hey, @Sne2003 

Why it is still showing a minus sign "-" before the date, hour, minute and second?
![image](https://github.com/Upasana1807/Electoral-Application/assets/155513433/6c4f92b6-87b2-44b4-84a4-752cd394cabd)

**Comment by Sne2003** [comment]
Hey @Upasana1807,

The issue has been solved.

![image](https://github.com/Upasana1807/Electoral-Application/assets/127588865/71a5a597-af41-47b0-a013-3e76a8bad5af)
