### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by Sne2003** [Upasana1807/Electoral-Application#72]
Hey @Upasana1807,

Please look after this and solve it.

![Screenshot 2024-05-12 015750](https://github.com/Upasana1807/Electoral-Application/assets/127588865/5032b6b7-b049-4912-8198-17448ebbc18f)

**Comment by Upasana1807** [comment]
Hey, @Sne2003 please pull the latest code. This problem is already solved and merged.

**Comment by Sne2003** [comment]
Ok
